### ISSUE TITLE
Unmatched patterns: TIntersection | TNamed

### ISSUE THREAD

**Issue by hamaluik** [dpomier/haxe-yield#1]
I love the idea of this, but so far I haven't been able to use it. I always get these errors:

```
./lib/yield/yield/parser/YieldSplitter.hx:349: characters 11-12 : Unmatched patterns: TIntersection | TNamed
./lib/yield/yield/parser/tools/MetaTools.hx:250: characters 11-12 : Unmatched patterns: TIntersection | TNamed
```

**Comment by dpomier** [comment]
You are probably compiling with Haxe 4, which is not supported yet. I am currently working on it though so it should work in the following days :)

I've updated the doc for now

**Comment by dpomier** [comment]
it is fixed on the development build, thanks :)
