### ISSUE TITLE
String should be Iterator<String>

### ISSUE THREAD

**Issue by CodestarGames** [dpomier/haxe-yield#8]
I'm trying to do the following with the 3.2.1 version of yield on haxe 4.3.2 and the onGenerate iterator function isn't recognized as an iterator by the compiler.

`
C:/devel/ceramic-samples/pixel-platformer/src/engine/actions/Action.hx:482: characters 11-49 : String should be Iterator<String>
C:/devel/ceramic-samples/pixel-platformer/src/engine/actions/Action.hx:482: characters 11-49 : ... String has no field hasNext
C:/devel/ceramic-samples/pixel-platformer/src/engine/actions/Action.hx:486: characters 10-50 : String should be Iterator<String>
C:/devel/ceramic-samples/pixel-platformer/src/engine/actions/Action.hx:486: characters 10-50 : ... String has no field hasNext
`

```
@:yield
class TestIterableAction extends IterableAction implements IIterableAction {
	var stepNum:Int = 0;

	public override function onStart() {}

	public override function onStep(step:Int) {
		trace(step);
		this.actor.x += 1;
		stepNum++;
	}

	public override function onComplete() {}

	public override function onGenerate():Iterator<String> {
		while (this.stepNum < 300) {
			@yield return ActionResult.RUNNING.toString();
		}

		trace("SUCCCCEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSS");
		@yield return ActionResult.SUCCEEDED.toString();
	}
}
```

**Comment by dpomier** [comment]
I hope you were able to resolve the issue. Let me know otherwise.
